Repository framgia/sph-classroom-els-fe, pull requests merged in 2021-11, with the labels that each got.

#14 E_CLASSROOM-43 [Frontend] [Student] [Markup] User Authentication 2/2
  src/pages/student/main/Registration/index.js
  src/pages/student/main/Registration/index.module.css
Labels: Approved by Geneno, For Code Review

#13 Feature/e classroom 42 markup student user authentication markup
  src/components/App.js
  src/components/css/GlobalStyle.css
  src/components/users/Login.js
  src/components/users/Login.module.css
  src/pages/student/main/Login/index.js
  src/pages/student/main/Login/index.module.css
Labels: Approved by Geneno, Approved by Erron, For Code Review

#9 E_CLASSROOM-41 [Markup] [Student] Categories
  public/index.html
  src/components/css/GlobalStyle.css
  src/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
Labels: Approved by Geneno, For Code Review

#6 E_CLASSROOM-117 [Markup] [Student] Password Reset
  src/components/css/GlobalStyle.css
  src/components/users/NewPassword.js
  src/components/users/PasswordReset.js
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/NewPassword/index.module.css
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/PasswordReset/index.module.css
  src/routes/index.js
  yarn.lock
Labels: Approved by Geneno, Erron is Reviewing, For Code Review

#5 Feature/e classroom 47 markup student create dashboard markup
  src/components/css/GlobalStyle.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
  yarn.lock
Labels: Approved by Geneno, Approved by Erron

#12 E_CLASSROOM-44 [Frontend] [Student] [Markup] User Profile 1/3
  src/components/App.js
  src/components/css/GlobalStyle.css
  src/components/users/StudentProfile.js
  src/components/users/StudentProfile.module.css
  src/index.js
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/stylecss/GlobalStyle.css
Labels: Approved by Geneno, Approved by Erron

#11 Feature/e classroom 50 markup student quizzes 2/3
  src/components/App.js
  src/index.js
  src/pages/student/main/NewPassword/index.module.css
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuestionList/index.module.css
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/routes/index.js
Labels: Approved by Geneno, Erron is Reviewing

#16 E_CLASSROOM-49 [Frontend] [Student] [Markup] Quizzes Page
  package-lock.json
  package.json
  src/components/App.js
  src/components/Navbar.js
  src/components/Pagination/index.js
  src/components/Pagination/index.module.css
  src/components/css/GlobalStyle.css
  src/components/css/QuizRightAnswerResult.css
  src/components/css/Result.css
  src/components/users/Login.js
  src/components/users/Login.module.css
  src/components/users/NewPassword.js
  src/components/users/PasswordReset.js
  src/components/users/StudentProfile.js
  src/components/users/StudentProfile.module.css
  src/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/main/Registration/index.js
  src/pages/student/profile/ChangePassword/index.js
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/students/StudentList/ChangeDatails/index.js
  src/stylecss/GlobalStyle.css
  src/styles/index.css
  src/styles/theme.js
  yarn.lock
Labels: Approved by Mary Therese

#21 E_CLASSROOM-120 [Integration] [Frontend] [Student] [Markup] Quizzes 1/2
  src/api/Quiz/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
Labels: Approved by Erron, Approved by Paul Erick

#20 E_CLASSROOM-104 [Frontend] [Student] [Integration] User Authentication 2/2
  src/api/Auth/index.js
  src/pages/student/main/Registration/index.js
Labels: Approved by Erron, For Code Review, Approved by John Harvey

#18 E classroom 113 integration student categories
  src/api/Category/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
Labels: Approved by Erron, Approved by Paul Erick

#22 Feature/e classroom 118 integration student password reset
  src/api/PasswordReset/index.js
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/NewPassword/index.module.css
  src/pages/student/main/PasswordReset/index.js
  src/routes/index.js
Labels: Approved by Erron

#26 E_CLASSROOM-158 [FE][Linters] Fix Linter errors
  src/api/Base/index.js
  src/components/Pagination/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/Registration/index.js
  src/pages/student/profile/ChangePassword/index.js
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentList/ChangeDatails/index.js
  src/pages/student/students/StudentList/index.js
  src/routes/middleware/AuthRoute/index.js
  src/routes/middleware/StudentRoute/index.js
Labels: Approved by Geneno, Approved by Erron

#25 E_CLASSROOM-141 [Markup] [Student] Subcategories Page
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/main/Registration/index.js
  src/routes/index.js
Labels: Approved by Geneno, Approved by Erron

#28 E_CLASSROOM-159 [Bugfix] [Student] Error at Registration Page
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/main/Registration/index.js
Labels: Approved by Geneno, Approved by Erron

#29 E_CLASSROOM-121 [Integration] [Frontend] [Student] Quiz Questions
  package-lock.json
  src/api/Question/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/students/StudentList/ChangeDatails/index.js
  src/routes/index.js
Labels: Approved by Erron, Approved by Lim

#27 E_CLASSROOM-138 [Integration] [Student] Quiz List Pagination
  src/api/Category/index.js
  src/api/Quiz/index.js
  src/components/Pagination/index.js
  src/components/Pagination/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
Labels: Approved by Geneno, Erron is Reviewing

#30 E_CLASSROOM-151 [Improvement] [Student] Update UI for student pages 1/6
  src/pages/student/main/Login/index.js
  src/pages/student/main/Login/index.module.css
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/NewPassword/index.module.css
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/PasswordReset/index.module.css
  src/pages/student/main/Registration/index.js
  src/pages/student/main/Registration/index.module.css
  src/styles/index.css
Labels: Approved by Erron, Approved by Lim

#34 E_CLASSROOM-142 [Integration] [Student] Subcategories Page
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/students/StudentList/ChangeDatails/index.js
Labels: Approved by Geneno, Approved by Erron

#32 E_CLASSROOM-143 [Integration] [Student] [Backend] [Frontend] Taking Student Quizzes
  src/api/Answer/index.js
  src/api/QuizTaken/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuizResult/index.js
Labels: Approved by Erron, Approved by Lim

#33 E_CLASSROOM-153 [Improvement] [Student] Update UI for student pages 3/6
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/EditProfile/index.module.css
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/profile/ProfileView/index.module.css
Labels: Approved by Erron, Approved by Lim

#36 E_CLASSROOM-157 [Integration] [Markup] [Student] Subcategory List Pag…
  src/api/Category/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryList/index.js
Labels: Approved by Erron, Approved by Lim

#37 E_CLASSROOM-137 [Integration] [Markup] [Student] Category List Pagina…
  src/api/Category/index.js
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
Labels: Approved by Geneno, Approved by Erron

#31 E_CLASSROOM-152 [Improvement] [Student] Update UI for student pages 2/6
  public/index.html
  src/components/AuthNavigationBar/index.js
  src/components/AuthNavigationBar/index.module.css
  src/components/NavigationBar/index.js
  src/components/NavigationBar/index.module.css
  src/pages/student/main/Dashboard/components/CategoryLearned/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.module.css
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Erron is Reviewing, Approved by Lim

#35 Feature/e classroom 154 improvement student update UI for student pages markup
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
Labels: Approved by Geneno, Erron is Reviewing

#39 E_CLASSROOM-163 [Frontend] Pagination position
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/categories/CategoryList/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
Labels: Approved by Geneno, Approved by Erron

#40 [Improvement] [Student] Update UI for student pages 5/6
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuestionList/index.module.css
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
  src/pages/student/quizzes/QuizResult/index.js
Labels: Erron is Reviewing, Approved by Lim

#41 E_CLASSROOM-171 [Bugfix] [FE] [Student] Fix Ordering of Categories if…
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/categories/CategoryList/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
Labels: Erron is Reviewing, Approved by Lim

#43 E_CLASSROOM-178 [FE] [Markup] [Student] Student List Page
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
  src/styles/index.css
Labels: Approved by Geneno, Approved by Erron

#45 E_CLASSROOM-179 [FE] [Integration] [Student] Student List Page
  src/api/Student/index.js
  src/pages/student/students/StudentDetail/ChangeDatails/changepass.module.css
  src/pages/student/students/StudentDetail/ChangeDatails/index.js
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Approved by Erron
