Repository framgia/sph-classroom-els-fe, pull requests merged in 2021-12, with the labels that each got.

#46 E_CLASSROOM-185 [FE] [Markup] [Student] Student Detail Page
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
  src/routes/index.js
Labels: Approved by Geneno, Approved by Erron

#44 E_CLASSROOM-195 [FE] [Integration] Student-List-Page-Search-Functionality
  src/api/Student/index.js
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Approved by Erron, Approved by Lim

#47 Feature/e classroom 194 fe integration student list pagination
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Approved by Erron, Approved by Lim

#48 Feature/e classroom 189 student improvement user authentication pages validation
  src/pages/student/main/Login/index.js
  src/pages/student/main/Login/index.module.css
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/Registration/index.js
  src/pages/student/main/Registration/index.module.css
Labels: Approved by Erron, Approved by Lim

#49 E_CLASSROOM-162 [Improvement] [Markup] Icons Update
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentList/index.js
Labels: Approved by Erron

#50 E_CLASSROOM-168 [FE] [Student] [Integration] Categories Learned Funcionality
  src/api/Dashboard/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Erron is Reviewing

#51 E_CLASSROOM-186 [FE] [Integration] [Student] Student Detail Page
  package-lock.json
  package.json
  src/api/QuizTaken/index.js
  src/api/Student/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuestionList/index.module.css
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
  src/pages/student/students/StudentList/index.js
  yarn.lock
Labels: wip, Erron is Reviewing, Approved by Lim

#52 E_CLASSROOM-190 [FE] [Improvement] [Student] Navigation Bar
  src/components/AuthNavigationBar/index.module.css
  src/components/NavigationBar/index.js
  src/components/NavigationBar/index.module.css
Labels: Approved by Erron, Approved by Lim

#54 E_CLASSROOM-170 [FE] [Student] Integration for Friends Activities
  src/api/Dashboard/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/index.js
Labels: Approved by Royce, For Code Review, Approved by Lim

#55 Feature/ E_Classroom 197 FE Integration of Student Activity in Student Detail Page
  src/api/Student/index.js
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
Labels: For Code Review, Approved by Lim

#53 E_CLASSROOM-166 [FE] [Student] [Integration] Recent Activity Function…
  src/api/QuizTaken/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Approved by Royce, Approved by Geneno, For Code Review

#57 E_CLASSROOM-192 [FE] [BE] [Student] [Improvement] Quiz Results Page F…
  src/api/FriendsScore/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Approved by Royce, Approved by Geneno

#56 E_CLASSROOM-200 [Bugfix] Dashboard table is overlapping
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Approved by Royce, Approved by Geneno, For Code Review

#58 E_CLASSROOM-202 [Bugfix] Dashboard table display issue
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Approved by Royce, For Code Review, Approved by Lim

#60 E_CLASSROOM-205 [Bugfix] Fix Recents Cards in Dashboard
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Approved by Royce, For Code Review, Approved by Lim
