Repository framgia/sph-classroom-els-fe, pull requests merged in 2022-01, with the labels that each got.

#62 E_CLASSROOM-206 [Bugfix] Follow and Unfollow Button Default Color
  src/pages/student/students/StudentDetail/index.module.css
  src/pages/student/students/StudentList/index.module.css
Labels: Royce is reviewing, For Code Review, Joash is reviewing, Approved by Joash

#70 E_CLASSROOM-209 FE Category Sort Function
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#71 E_CLASSROOM-218 [Bugfix] Quizzes Score Exceeds The Total Number
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#65 E_CLASSROOM-213 [FE/BE] Update display Friends score if empty
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Approved by Geneno, Approved by John Harvey

#69 E_CLASSROOM-210 FE Category Filter Function
  src/api/Category/index.js
  src/components/NavigationBar/index.module.css
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.css
Labels: For Code Review, Approved by John Harvey

#67 E_CLASSROOM-211 FE Category Search Function
  src/pages/student/categories/CategoryList/index.js
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#61 E_CLASSROOM-204 [FE/BE] Make Category Quizzes page dynamic
  src/api/QuizTakenReview/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css
Labels: Approved by Royce, Approved by Lim

#74 E_CLASSROOM-217 FE User and Friend Activities
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#63 E_CLASSROOM-214 [FE/BE] Avatar of friends in result page is not showi…
  .eslintrc.json
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Approved by Royce, Approved by John Harvey, Approved by Lim

#75 E_CLASSROOM-219 [Bugfix] Navbar Dropdown Menu Shrunk
  src/components/NavigationBar/index.js
  src/components/NavigationBar/index.module.css
Labels: Approved by Royce, For Code Review, Approved by John Harvey

#72 E_CLASSROOM-212 [FE] Update Password Reset Validation
  .eslintrc.json
  src/components/NavigationBar/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/main/Dashboard/components/CategoryLearned/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/PasswordReset/index.module.css
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/components/MultipleChoiceType/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentList/index.js
Labels: Approved by John Harvey, Inah is reviewing

#78 E_CLASSROOM-221 [Bugfix] Bonus Score is Added When Time Is Up
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
Labels: For Code Review, Approved by John Harvey

#77 E_CLASSROOM-220 [Bugfix] Avatars in Students List is Not Showing
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Approved by John Harvey

#80 E_CLASSROOM-238 [Bugfix] Other User's Quiz Log Avatar is Not Showing
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#79 E_CLASSROOM-226 [Bugfix] Remove Friend's Score UI If There's No Friends Score
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#82 E_CLASSROOM-242 [Admin] [UI] Overall Layout
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
  src/routes/index.js
  src/routes/middleware/AdminRoute/index.js
Labels: Approved by Mary Therese, Approved by Karlo

#76 E_CLASSROOM-215-FE/BE-Profile-Edit-Function - first commit
  src/api/ProfileEdit/index.js
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/EditProfile/index.module.css
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/profile/ProfileView/index.module.css
Labels: John Harvey is Reviewing, Karlo is reviewing

#83 E_CLASSROOM-241 [Admin] FE Implement Admin Login
  src/api/Auth/index.js
  src/pages/admin/main/Login/index.js
  src/pages/admin/main/Login/index.module.css
  src/pages/student/main/Login/index.js
  src/routes/index.js
  src/routes/middleware/AdminRoute/index.js
  src/routes/middleware/AuthRoute/index.js
  src/routes/middleware/StudentRoute/index.js
  src/services/AuthService.js
Labels: Approved by John Harvey, Approved by Karlo
