Repository framgia/sph-classroom-els-fe, pull requests merged in 2022-03, with the labels that each got.

#120 E_CLASSROOM-296 [FE] Create a reusable table component
  src/components/DataTable/index.js
  src/components/DataTable/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#119 E_CLASSROOM-289 [Bugfix] Layout is broken if screen is small
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by Paul Erick, Approved by Karlo

#121 E_CLASSROOM-282 [FE/BE] Invite Admin User
  src/api/Admin/index.js
  src/pages/admin/Admin/CreateAdmin/index.js
  src/pages/admin/Admin/CreateAdmin/index.module.scss
  src/pages/admin/Admin/SetAdminPassword/index.js
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#123 E_CLASSROOM-283 [FE/BE] Admin Invitation Acceptance
  src/api/Admin/index.js
  src/pages/admin/Admin/SetAdminPassword/index.js
  src/pages/admin/Admin/SetAdminPassword/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#122 E_CLASSROOM-284 [FE/BE] Update Account Info
  src/api/Admin/index.js
  src/api/ProfileEdit/index.js
  src/pages/admin/profile/EditProfile/index.js
  src/pages/admin/profile/EditProfile/index.module.scss
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#126 hotfix change-url
  src/api/ProfileEdit/index.js
  src/pages/admin/profile/EditProfile/index.js
Labels: Approved by John Harvey, Approved by Karlo

#127 E_CLASSROOM-300 [Bugfix] Password field should not update password
  src/api/ProfileEdit/index.js
  src/components/NavigationSideBar/index.js
  src/pages/admin/profile/EditProfile/index.js
  src/pages/admin/profile/Profile/index.js
  src/routes/index.js
Labels: Approved by Mary Therese, Karlo is reviewing

#125 E_CLASSROOM-288 (Dependent #296) [FE/BE] Quizzes Sort by Column
  src/components/DataTable/index.js
  src/components/DataTable/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#128 E_CLASSROOM-299 [FE/BE] [Admin] Change Password Page
  src/api/Admin/index.js
  src/pages/admin/profile/EditPassword/index.js
  src/pages/admin/profile/EditPassword/index.module.scss
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#129 E_CLASSROOM-297 [Bugfix] Edit Category can have an identical title
  src/pages/admin/categories/AddEditCategory/index.js
Labels: Approved by John Harvey, Approved by Karlo

#130 E_CLASSROOM-276 [FE/BE] Accounts List Page
  src/api/Admin/index.js
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/Admin/AdminList/index.module.scss
  src/routes/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#131 E_CLASSROOM-286 (Dependent #288) [FE/BE] Categories sort by column
  src/api/Category/index.js
  src/components/DataTable/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by Mary Therese, Karlo is reviewing

#132 E_CLASSROOM-303 [FE/BE] Category Hierarchy Page
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryHierarchy/index.module.scss
  src/routes/index.js
  src/styles/_variables.scss
Labels: Approved by John Harvey, Karlo is reviewing

#133 E_CLASSROOM-291 [Bugfix] Content area should be full
  src/components/DataTable/index.module.scss
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/categories/AddEditCategory/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizDetail/index.js
  src/pages/admin/quizzes/QuizDetail/index.module.scss
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
  src/pages/admin/quizzes/QuizList/components/AddQuizModal/index.js
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
  src/styles/global-styles.scss
Labels: Approved by Mary Therese, Karlo is reviewing

#134 E_CLASSROOM-298 [FE/BE] [Admin] Profile Account Page
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/profile/EditProfile/index.js
  src/pages/admin/profile/Profile/index.js
  src/pages/admin/profile/ProfileView/components/ModalData/index.js
  src/pages/admin/profile/ProfileView/index.js
  src/pages/admin/profile/ProfileView/index.module.scss
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#135 E_CLASSROOM-304 (Dependent on #303) [FE/BE] Category dropdown actions
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryHierarchy/index.module.scss
  src/styles/_variables.scss
Labels: Approved by John Harvey, Approved by Karlo

#136 E_CLASSROOM-295 [Admin] [FE/BE] Admin User search by name or email
  src/pages/admin/Admin/AdminList/index.js
  src/pages/student/categories/CategoryList/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#138 E_CLASSROOM-308 (Dependent on #303) [FE/BE] Breadcrumbs for Hierarchy Page
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryHierarchy/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#137 E_CLASSROOM-309 [Bugfix] [Student] Cannot upload photo unless refresh
  src/pages/student/profile/ProfileDetail/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#139 E_CLASSROOM-280 [FE/BE] Sort admin table by column
  src/components/DataTable/index.js
  src/components/DataTable/index.module.scss
  src/pages/admin/Admin/AdminList/index.js
Labels: Approved by John Harvey, Approved by Karlo

#141 E_CLASSROOM-301 [FE/BE] [Admin] Filtering quizzes by name and category
  src/components/DataTable/index.module.scss
  src/components/FilterDropdown/index.js
  src/components/FilterDropdown/index.module.scss
  src/components/SearchBar/index.js
  src/components/SearchBar/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: John Harvey is Reviewing, Karlo is reviewing

#142 E_CLASSROOM-293 [Admin] [FE/BE] Categories search by name
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#118 E_CLASSROOM-279 [FE/BE] Implement the add/edit of a question
  src/api/Question/index.js
  src/pages/admin/quizzes/QuizEdit/components/IdentificationType/index.js
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/components/QuestionType/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#143 E_CLASSROOM-318 [Admin] [FE] Create themes page
  src/pages/admin/Theme/index.js
  src/routes/index.js
  src/routes/middleware/AdminRoute/index.js
Labels: Approved by Paul Erick, Approved by Karlo

#146 E_CLASSROOM-306 [FE] Reusable Dropdown Component
  src/components/FilterDropdown/index.js
  src/components/FilterDropdown/index.module.scss
  src/pages/admin/Theme/components/dropdown.js
  src/pages/admin/Theme/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#145 E_CLASSROOM-325 [FE/BE] Apply comments in the add/edit questions
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
Labels: Approved by Paul Erick, Approved by Karlo

#147 E_CLASSROOM-314 [FE/BE] Implement Delete a Question
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
  src/styles/_variables.scss
Labels: Approved by John Harvey, Karlo is reviewing

#148 E_CLASSROOM-307 [FE] Reusable Button Component
  src/components/Button/index.js
  src/components/Button/index.module.scss
  src/pages/admin/Theme/components/button.js
  src/pages/admin/Theme/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/styles/_variables.scss
Labels: Approved by Paul Erick, Karlo is reviewing

#149 E_CLASSROOM-305 [FE] Reusable Input Component
  src/components/InputField/index.js
  src/components/InputField/index.module.scss
  src/pages/admin/Theme/components/input.js
  src/pages/admin/Theme/index.js
Labels: Approved by John Harvey, Approved by Karlo

#150 E_CLASSROOM-311 [Admin] Move Action Buttons
  src/components/Button/index.js
  src/components/DataTable/index.js
  src/components/SearchBar/index.js
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#151 E_CLASSROOM-323 [FE/BE] Display Breadcrumbs for Categories
  src/components/Breadcrumbs/index.js
  src/components/Breadcrumbs/index.module.scss
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryHierarchy/index.module.scss
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/categories/CategoryDetail/index.module.scss
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#154 E_CLASSROOM-328 [FE/BE] Delete for Quizzes and Admin Table
  src/api/Admin/index.js
  src/api/Quiz/index.js
  src/components/ConfirmationModal/index.js
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by John Harvey, Approved by Karlo

#155 E_CLASSROOM-333 [FE/BE] Apply Reusable Components to /learnings
  src/components/DataTable/index.module.scss
  src/pages/student/learnings/LearningList/component/index.js
  src/pages/student/learnings/LearningList/component/index.module.scss
  src/pages/student/learnings/LearningList/index.js
  src/pages/student/learnings/LearningList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#156 [Hotfix] Remove profile picture edit functionality
  src/api/ProfileEdit/index.js
  src/pages/admin/profile/ProfileView/index.js
  src/pages/admin/profile/ProfileView/index.module.scss
  src/pages/student/profile/ProfileDetail/index.js
Labels: Approved by Mary Therese, Approved by John Harvey

#157 E_CLASSROOM-316 [Student] [FE/BE] Remove the View all in student dash…
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
Labels: Approved by Mary Therese, Approved by Karlo

#152 E_CLASSROOM-337 [FE/BE] Fix change category in add/edit question
  src/api/Question/index.js
  src/components/ChangeLocation/component/Location/index.js
  src/pages/admin/quizzes/QuizDetail/index.js
  src/pages/admin/quizzes/QuizDetail/index.module.scss
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
Labels: John Harvey is Reviewing, Approved by Karlo

#153 E_CLASSROOM-324 [FE/BE] Display related subcategories and quizzes for the selected category
  src/api/Quiz/index.js
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.scss
  src/styles/_variables.scss
Labels: Approved by John Harvey, Approved by Karlo

#159 E_CLASSROOM-320 [UI] FIx header layout
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.css
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.scss
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.scss
  src/pages/student/learnings/LearningList/index.js
  src/pages/student/learnings/LearningList/index.module.scss
  src/pages/student/main/Dashboard/components/CategoryLearned/index.module.css
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
  src/pages/student/main/Login/index.js
  src/pages/student/main/Login/index.module.scss
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/NewPassword/index.module.scss
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/PasswordReset/index.module.scss
  src/pages/student/main/Registration/index.js
  src/pages/student/main/Registration/index.module.scss
  src/pages/student/profile/EditProfile/index.module.css
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/pages/student/profile/ProfileView/index.module.css
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.css
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuestionList/index.module.css
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
  src/pages/student/quizzes/QuizResult/index.module.css
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#161 E_CLASSROOM-338 [Admin] [FE] Apply reusable components to table list pages
  src/components/SearchBar/index.js
  src/components/SearchBar/index.module.scss
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by Paul Erick, Approved by Karlo

#165 E_CLASSROOM-332 [FE/BE] Apply reusable components to /profile
  src/components/InputField/index.js
  src/components/InputField/index.module.scss
  src/pages/student/profile/ChangePassword/index.js
  src/pages/student/profile/ChangePassword/index.module.css
  src/pages/student/profile/ChangePassword/index.module.scss
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/EditProfile/index.module.css
  src/pages/student/profile/EditProfile/index.module.scss
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
  src/pages/student/profile/ProfileDetail/index.module.scss
  src/pages/student/profile/ProfileView/index.js
  src/pages/student/profile/ProfileView/index.module.css
  src/pages/student/profile/ProfileView/index.module.scss
Labels: Approved by Joash, Karlo is reviewing

#160 E_CLASSROOM-326 [FE/BE] Move To function in Category Hierarchy Page
  src/components/ChangeLocation/component/Location/index.js
  src/components/ChangeLocation/index.js
  src/pages/admin/categories/CategoryHierarchy/index.js
Labels: Approved by Joash, Karlo is reviewing

#162 E_CLASSROOM-321 [UI] Fix content width and inconsistencies of all pages
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.js
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.scss
  src/pages/student/categories/CategoryDetail/index.module.scss
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.module.scss
  src/pages/student/learnings/LearningList/index.module.scss
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.css
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.scss
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.css
  src/pages/student/main/Dashboard/components/Recent/index.module.scss
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.css
  src/pages/student/profile/ChangePassword/index.js
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/ProfileDetail/index.module.scss
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.scss
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.scss
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.scss
  src/styles/_variables.scss
Labels: Approved by Paul Erick, Karlo is reviewing

#168 E_CLASSROOM-341 [Admin] [FE] Apply reusable components to Admin user/account pages
  src/pages/admin/Admin/CreateAdmin/index.js
  src/pages/admin/Admin/CreateAdmin/index.module.scss
  src/pages/admin/Admin/SetAdminPassword/index.js
  src/pages/admin/Admin/SetAdminPassword/index.module.scss
  src/pages/admin/main/Login/index.js
  src/pages/admin/main/Login/index.module.css
  src/pages/admin/main/Login/index.module.scss
  src/pages/admin/profile/EditPassword/index.js
  src/pages/admin/profile/EditPassword/index.module.scss
  src/pages/admin/profile/EditProfile/index.js
  src/pages/admin/profile/EditProfile/index.module.scss
  src/pages/admin/profile/ProfileView/index.js
  src/pages/admin/profile/ProfileView/index.module.scss
Labels: John Harvey is Reviewing, Karlo is reviewing

#163 E_CLASSROOM-329 [FE/BE] Category Delete Function
  src/api/Category/index.js
  src/components/ConfirmationModal/index.js
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryList/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#164 E_CLASSROOM-339 [Admin] [FE] Apply reusable components to Category forms
  src/components/Button/index.js
  src/components/InputField/index.js
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#169 E_CLASSROOM-343 [Bugfix] User can input admin email in student forget password
  src/pages/student/main/PasswordReset/index.js
Labels: Approved by John Harvey, Approved by Karlo

#172 E_CLASSROOM-345 [Bugfix] User name in admin sidebar is not dynamic
  src/components/NavigationSideBar/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#167 E_CLASSROOM-340 [Admin] [FE] Apply reusable components to Quiz view pages and forms
  src/components/FilterDropdown/index.js
  src/components/InputField/index.js
  src/pages/admin/Theme/components/dropdown.js
  src/pages/admin/quizzes/QuizEdit/components/IdentificationType/index.js
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/components/QuestionType/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
  src/pages/admin/quizzes/QuizList/components/AddQuizModal/index.js
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#173 E_CLASSROOM-334 [FE/BE] Apply reusable components to /dashboard
  src/components/DataTable/index.js
  src/components/DataTable/index.module.scss
  src/pages/student/main/Dashboard/components/CategoryLearned/index.module.css
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/index.js
  src/pages/student/main/Dashboard/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#176 E_CLASSROOM-349 [FE/BE][Admin] Add Category Hierarchy in the sidebar
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/categories/CategoryList/index.js
Labels: Approved by Mary Therese, Karlo is reviewing

#175 E_CLASSROOM-346 [Bugfix] Choices from previous question appears on click of next question
  src/pages/admin/quizzes/QuizEdit/components/IdentificationType/index.js
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/components/QuestionType/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#177 E_CLASSROOM-348 [Bugfix] Quiz title in /categories is not truncated
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
  src/pages/student/categories/CategoryDetail/components/SubcategoryCard/index.module.scss
  src/pages/student/categories/CategoryDetail/index.module.scss
  src/pages/student/categories/CategoryList/index.module.scss
  src/pages/student/main/Dashboard/components/Recent/index.module.scss
  src/pages/student/main/Dashboard/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#178 E_CLASSROOM-355 [Bugfix] Remove profile picture icon in admin sidebar and /students
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.scss
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#179 E_CLASSROOM-354 [Bugfix][Admin] User name will not update after name update
  src/components/NavigationSideBar/index.js
  src/context/adminContext.js
  src/pages/admin/main/Login/index.js
  src/pages/admin/profile/EditProfile/index.js
  src/routes/middleware/AdminRoute/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#180 E_CLASSROOM-356 [Bugfix] Sorting/Searching a table should reset to page 1
  src/components/SearchBar/index.js
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#181 E_CLASSROOM-357 [Bugfix] Clicking on the cancel button redirects to blank page
  src/pages/admin/Admin/CreateAdmin/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#182 E_CLASSROOM-358 [Bugfix] Deleting with only one data will stay in the same page
  src/pages/admin/Admin/AdminList/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#183 E_CLASSROOM-353 [Admin][Category] Remove max length for category description
  src/pages/admin/categories/CategoryList/index.module.scss
Labels: John Harvey is Reviewing, Karlo is reviewing

#184 E_CLASSROOM-352 [Bugfix] Fix height of the admin page
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
Labels: Approved by Paul Erick, Karlo is reviewing

#185 E_CLASSROOM-359 [Bugfix] Choice text is not truncated if it is too long
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#186 E_CLASSROOM-363 [Bugfix] Activities card layout is broken
  src/components/DataTable/index.module.scss
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.scss
  src/pages/student/main/Dashboard/index.module.scss
Labels: Approved by Paul Erick, Karlo is reviewing

#188 E_CLASSROOM-361 [Bugfix] Recent and Friend activities should have the same min-height
  src/pages/student/profile/ProfileDetail/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#187 E_CLASSROOM-364 [Bugfix] Error occurs when input text too long in edi…
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#189 E_CLASSROOM-365 [Bugfix] Space for card is present even though there is no content
  src/api/Quiz/index.js
  src/pages/student/categories/CategoryDetail/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#190 E_CLASSROOM-366 [Bugfix] [Admin] Name of the login user is broken
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.scss
  src/styles/_variables.scss
Labels: Approved by Mary Therese, Karlo is reviewing

#191 E_CLASSROOM-370 [Improvement] Add a section background if there is no related quiz
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.scss
Labels: Approved by Paul Erick, Karlo is reviewing

#193 E_CLASSROOM-371 [Bugfix] [Student] [Category list] When user Click all the spinner will spin infinite.
  src/pages/student/categories/CategoryList/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#192 E_CLASSROOM-369 [Bugfix] Quiz name is not truncated if it is too long
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/QuestionAnswer/indexQuestion.module.scss
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuestionList/index.module.scss
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.scss
  src/pages/student/quizzes/QuizList/index.module.scss
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.scss
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.scss
  src/styles/global-styles.scss
Labels: Approved by Joash, Karlo is reviewing

#194 E_CLASSROOM-372 [Bugfix] Card size in view quiz result is too small
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.scss
Labels: Mary Therese is Reviewing, Karlo is reviewing

#196 E_CLASSROOM-374 [Improvement][Admin] Change Action and Description column width
  src/pages/admin/Admin/AdminList/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#197 E_CLASSROOM-381 [Bugfix] Toaster is not displayed correctly
  src/components/Toaster/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#198 E_CLASSROOM-382 [Improvement][Student] Display only one spinner when retrieving quizzes and related quizzes
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#199 E_CLASSROOM-383 [Improvement][Student] Apply reusable components to students
  src/components/SearchBar/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#201 E_CLASSROOM-376 [Improvement][Admin] Add/Edit Category form Header an…
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
Labels: Approved by Paul Erick, Karlo is reviewing

#202 E_CLASSROOM-342 [FE/BE] Implement Change Password for Student Profile
  src/api/Student/index.js
  src/pages/student/profile/ChangePassword/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#204 E_CLASSROOM-368 [Bugfix] Dropdown option highlights the previously selected option
  src/components/FilterDropdown/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#200 E_CLASSROOM-373 [Improvement][Student] Update Recent and Follower Activities Card
  src/api/QuizTaken/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.js
  src/pages/student/main/Dashboard/components/FriendsActivities/index.module.scss
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.scss
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.scss
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.scss
  src/routes/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#203 E_CLASSROOM-386 [Bugfix] Moving a subcategory to root will not reflect
  src/pages/admin/categories/AddEditCategory/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#206 E_CLASSROOM-377 [Improvement] [Admin] [Student] Non-authenticated snackbar and modal message
  src/components/ConfirmationModal/index.js
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.scss
  src/pages/admin/categories/CategoryHierarchy/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/main/Login/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/Registration/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#208 E_CLASSROOM-379 [Improvement] [Student] Update quizzes header on categories
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.js
  src/pages/student/categories/CategoryDetail/components/QuizzesCard/index.module.scss
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/main/Dashboard/components/Recent/index.module.scss
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.js
  src/pages/student/quizzes/QuizList/components/QuestionGrid/index.module.scss
  src/pages/student/quizzes/QuizList/index.module.scss
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/styles/global-styles.scss
Labels: Approved by John Harvey, Karlo is reviewing

#207 E_CLASSROOM-378 [Improvement] [Student] Removing Retake quiz button
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/quizzes/QuizResult/index.js
Labels: Approved by Mary Therese, Karlo is reviewing

#210 E_CLASSROOM-384 [Improvement][Student] Implement sort in /learnings table
  src/components/DataTable/index.js
  src/pages/student/learnings/LearningList/index.js
  src/pages/student/learnings/LearningList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#211 E_CLASSROOM-380 [Improvement][Admin] Edit quiz name and UI fix
  src/api/Question/index.js
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.scss
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#209 E_CLASSROOM-388 [Bugfix] When student name is too long the button is misplaced
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.scss
Labels: Approved by John Harvey, Karlo is reviewing

#212 E_CLASSROOM-387 [Bugfix] Clicking on the category name will popup the…
  src/pages/admin/categories/CategoryHierarchy/index.js
Labels: Approved by Mary Therese, Karlo is reviewing

#213 E_CLASSROOM-390 [Bugfix] Choice is highlighted when clicking next question
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/MultipleChoiceType/index.js
Labels: Approved by John Harvey, Karlo is reviewing

#214 E_CLASSROOM-389 [Bugfix] Go back button not correctly displayed
  src/components/ChangeLocation/index.js
  src/components/ChangeLocation/index.module.scss
  src/pages/admin/categories/AddEditCategory/index.js
Labels: Approved by Mary Therese, Karlo is reviewing
