Repository framgia/sph-classroom-els-fe, pull requests merged in 2022-02, with the labels that each got.

#87 E_CLASSROOM-229 [Admin] [UI] Category List Page
  package-lock.json
  package.json
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.css
  src/pages/admin/categories/CategoryList/index.module.scss
  src/routes/index.js
  yarn.lock
Labels: Approved by John Harvey, Approved by Karlo

#59 E_CLASSROOM-193 [FE] [BE] [Student] [Improvement] Quiz Results Page R…
  src/api/Quiz/index.js
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.module.css
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Royce is reviewing, Approved by Lim

#88 E_CLASSROOM-235 [FE] [BE] [Student] [Improvement] Implement A Toaster
  src/components/NavigationBar/index.js
  src/components/Toaster/index.js
  src/context/ToastContext.js
  src/hooks/useToast.js
  src/index.js
  src/pages/admin/main/Login/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/main/NewPassword/index.js
  src/pages/student/main/PasswordReset/index.js
  src/pages/student/main/Registration/index.js
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/EditProfile/index.module.css
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentList/index.js
Labels: Approved by John Harvey, Approved by Karlo

#89 E_CLASSROOM-245 [Bugfix] Quiz results are not centered
  src/pages/student/quizzes/QuestionList/QuestionAnswer/index.js
  src/pages/student/quizzes/QuestionList/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.js
  src/pages/student/quizzes/QuizResult/Recent/index.module.css
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/quizzes/QuizResult/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#91 E_CLASSROOM-234 [Admin] [FE/BE] Dynamic Data for Displaying Categories List
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#90 E_CLASSROOM-231 Category Add/Edit Form
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/categories/AddCategory/index.js
  src/pages/admin/categories/AddCategory/index.module.css
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
  src/pages/admin/categories/EditCategory/index.js
  src/pages/admin/categories/EditCategory/index.module.css
  src/routes/index.js
  src/routes/middleware/AdminRoute/index.js
Labels: Mary Therese is Reviewing, Approved by Karlo

#85 improvement/E_CLASSROOM-244-FE/BE-Profile-picture-upload
  src/api/ProfileEdit/index.js
  src/api/Student/index.js
  src/pages/student/profile/ProfileDetail/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
Labels: Approved by Mary Therese, Approved by Karlo

#86 [E_CLASSROOM-227]Sorting UI in Categories
  src/pages/student/categories/CategoryList/index.js
Labels: Approved by Mary Therese, Approved by John Harvey

#93 E_CLASSROOM-256 [Bugfix] Avatar in the Student List and Friend's Score section is not displaying properly
  src/pages/student/quizzes/QuizResult/index.js
  src/pages/student/students/StudentList/index.js
  src/pages/student/students/StudentList/index.module.css
Labels: Joash is reviewing, Approved by Joash, Karlo is reviewing

#92 E_CLASSROOM-246 [FE] [Improvement] Apply Global Variables for SASS Files
  src/pages/admin/categories/CategoryList/index.module.scss
  src/styles/_variables.scss
Labels: Approved by John Harvey, Karlo is reviewing

#94 E_CLASSROOM-236 [Student][Learnings][FE/BE] Display all quizzes
  src/api/Learning/index.js
  src/pages/student/categories/CategoryList/index.js
  src/pages/student/learnings/LearningList/component/index.js
  src/pages/student/learnings/LearningList/component/index.module.scss
  src/pages/student/learnings/LearningList/index.js
  src/pages/student/learnings/LearningList/index.module.css
  src/pages/student/learnings/LearningList/index.module.scss
  src/pages/student/main/Dashboard/components/Recent/index.js
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#95 E_CLASSROOM-267 [Bugfix] [Student details] avatar in the student deta…
  src/pages/student/students/StudentDetail/index.js
  src/pages/student/students/StudentDetail/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#98 E_CLASSROOM-264 [FE] [Improvement] Removed Success Toast for Login and Logout Functionality
  src/components/NavigationBar/index.js
  src/pages/admin/main/Login/index.js
  src/pages/student/main/Login/index.js
  src/pages/student/profile/EditProfile/index.js
Labels: John Harvey is Reviewing, Karlo is reviewing

#96 E_CLASSROOM-266 [FE] [Student] [Improvement] Profile Edit
  src/pages/student/profile/ProfileDetail/index.js
Labels: Approved by John Harvey, Approved by Karlo

#99 E_CLASSROOM-263 [FE] [Admin] [improvement] Categories description width and logout functionality
  src/components/NavigationSideBar/index.js
  src/pages/admin/categories/CategoryList/index.js
  src/pages/admin/categories/CategoryList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#97 Improvement/e classroom 268
  src/pages/admin/categories/AddEditCategory/index.module.scss
Labels: Approved by Mary Therese, Approved by Karlo

#100 E_CLASSROOM-248 [UI] Quizzes List Page
  src/components/NavigationSideBar/index.js
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
  src/routes/index.js
Labels: Approved by Mary Therese, Approved by Karlo

#101 E_CLASSROOM-250 [UI] Display Quiz Overview
  src/components/NavigationSideBar/index.module.css
  src/pages/admin/quizzes/QuizDetail/components/IdentificationAccordion/index.js
  src/pages/admin/quizzes/QuizDetail/components/MultipleChoiceAccordion/index.js
  src/pages/admin/quizzes/QuizDetail/components/index.module.scss
  src/pages/admin/quizzes/QuizDetail/index.js
  src/pages/admin/quizzes/QuizDetail/index.module.scss
  src/routes/index.js
  src/styles/_variables.scss
Labels: Approved by John Harvey, Karlo is reviewing

#102 E_CLASSROOM-249 [FE/BE] Display dynamic quizzes data
  src/api/Quiz/index.js
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by John Harvey, Approved by Karlo

#103 E_CLASSROOM-252 [UI] Markup for Edit Quiz Layout
  src/pages/admin/quizzes/QuizDetail/index.js
  src/pages/admin/quizzes/QuizDetail/index.module.scss
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
  src/routes/index.js
Labels: Approved by Paul Erick, Karlo is reviewing

#104 E_CLASSROOM-251 [FE/BE] Dynamic data for questions/choices
  src/pages/admin/quizzes/QuizDetail/components/IdentificationAccordion/index.js
  src/pages/admin/quizzes/QuizDetail/components/MultipleChoiceAccordion/index.js
  src/pages/admin/quizzes/QuizDetail/index.js
  src/pages/admin/quizzes/QuizDetail/index.module.scss
  src/pages/admin/quizzes/QuizList/index.js
Labels: Approved by Mary Therese, Approved by Karlo

#106 E_CLASSROOM-270 [Bugfix] Apply Red Color for Failed Scores and Apply Validation Error Messages for Duplicate Emails
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
Labels: For Code Review, Joash is reviewing

#108 E_CLASSROOM-260 [UI] Adding/Editing Nested Subcategories
  src/components/ChangeLocation/component/Location/index.js
  src/components/ChangeLocation/component/Location/index.module.scss
  src/components/ChangeLocation/index.js
  src/components/ChangeLocation/index.module.scss
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
  src/styles/_variables.scss
Labels: Approved by Joash, Approved by Karlo

#105 E_CLASSROOM-271 [Bugfix] Clicking on Categories Redirects to Blank Page
  src/components/NavigationSideBar/index.js
Labels: For Code Review, Approved by Joash

#107 E_CLASSROOM-253 [UI] Edit questions form
  src/pages/admin/quizzes/QuizEdit/components/IdentificationType/index.js
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/components/QuestionType/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
  src/pages/student/quizzes/QuestionList/QuestionAnswer/components/FillInTheBlankType/index.js
Labels: Approved by Mary Therese, Approved by Karlo

#111 E_CLASSROOM-272 [Bugfix] Back button is not a hand cursor
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.css
Labels: Approved by Paul Erick, Approved by Karlo

#109 E_CLASSROOM-255 [FE/BE] Implement adding a new quiz
  src/api/Quiz/index.js
  src/pages/admin/quizzes/QuizList/components/AddQuizModal/index.js
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
  src/pages/student/profile/EditProfile/index.js
  src/pages/student/profile/ProfileDetail/index.module.css
Labels: Approved by John Harvey, Approved by Karlo

#113 E_CLASSROOM-274 [Bugfix] Next button in the Results page has a differ…
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/index.js
  src/pages/student/quizzes/QuizResult/QuizAnswerResult/indexAnswer.module.css
Labels: Approved by Paul Erick, Approved by Karlo

#115 E_CLASSROOM-258 [Admin] [FE/BE] Add/Edit categories functionality
  src/api/Category/index.js
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
  src/pages/admin/categories/CategoryList/index.js
  src/routes/index.js
Labels: Approved by John Harvey, Approved by Karlo

#112 E_CLASSROOM-273 [Bugfix] Back button redirects to /categories if from…
  src/pages/student/categories/CategoryDetail/index.js
  src/pages/student/categories/CategoryDetail/index.module.css
  src/pages/student/quizzes/QuizList/index.js
  src/pages/student/quizzes/QuizList/index.module.css
Labels: Approved by Paul Erick, Karlo is reviewing

#110 E_CLASSROOM-261 [FE/BE] Moving Subcategories Functionality
  src/api/Category/index.js
  src/api/Quiz/index.js
  src/components/ChangeLocation/component/Location/index.js
  src/components/ChangeLocation/component/Location/index.module.scss
  src/components/ChangeLocation/index.js
  src/components/ChangeLocation/index.module.scss
  src/components/Toaster/index.js
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizList/components/AddQuizModal/index.js
  src/pages/admin/quizzes/QuizList/index.js
  src/pages/admin/quizzes/QuizList/index.module.scss
Labels: Approved by John Harvey, Approved by Karlo

#116 E_CLASSROOM-275 [Bugfix] Category name cannot be edited and description misleading error message
  src/pages/admin/categories/AddEditCategory/index.js
Labels: For Code Review, Approved by John Harvey

#114 E_CLASSROOM-254 [FE/BE] Implement adding a new question
  src/api/Question/index.js
  src/pages/admin/quizzes/QuizEdit/components/IdentificationType/index.js
  src/pages/admin/quizzes/QuizEdit/components/MultipleChoiceType/index.js
  src/pages/admin/quizzes/QuizEdit/components/QuestionType/index.js
  src/pages/admin/quizzes/QuizEdit/index.js
  src/pages/admin/quizzes/QuizEdit/index.module.scss
Labels: Approved by Paul Erick, Approved by Karlo

#117 E_CLASSROOM-277 [FE/BE] Implement Subcategory Functionality in Category Form
  src/api/Category/index.js
  src/components/ChangeLocation/component/Location/index.js
  src/components/ChangeLocation/index.js
  src/pages/admin/categories/AddEditCategory/index.js
  src/pages/admin/categories/AddEditCategory/index.module.scss
Labels: Approved by Paul Erick, Approved by Karlo
